version: '3'

services:
  app:
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    build:
      context: ./node
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    platform: linux/x86_64
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network


  # nginx:
  #   build:
  #     context: ./nginx
  #   image: lucasfigueiredom/node-nginx:latest
  #   container_name: nginx
  #   networks:
  #     - node-network
  #   ports:
  #     - "8080:80"


networks:
  node-network:
    driver: bridge